#!/bin/bash
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)

# add "here" to PATH
if ! echo $PATH | grep $here >/dev/null; then
  export PATH=$here:$PATH
fi

cd $here
set -o allexport; source .env; set +o allexport

_wait.sh psql -c 'select 1 as ok'
# wait for xserver (unlimited)
TIMEOUT=0 SLEEP=5 _wait.sh xinput

# run the pipeline
x-action-log | xinput2insert.sh | psql --quiet
