#!/bin/bash
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)

# add "here" to PATH
if ! echo $PATH | grep $here >/dev/null; then
  export PATH=$here:$PATH
fi

# run the pipeline
x-action-log | xinput2insert.sh | psql --quiet
