version: '3.5'

networks:
  ingress:
    external: true

services:

  db:
    image: timescale/timescaledb:latest-pg10
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql/create_apm.sql:/docker-entrypoint-initdb.d/z_01_create_apm.sql
      - ./sql/annotations.sql:/docker-entrypoint-initdb.d/z_02_annotations.sql
    restart: unless-stopped
  grafana:
    networks:
      default:
      ingress:
    labels:
      ingress.host: grafana.apm.x
      ingress.port: 3000
    # https://hub.docker.com/r/grafana/grafana/tags
    image: grafana/grafana:8.5.27
    environment:
      # something different than "admin", so grafana does not bug me to change it
      - GF_SECURITY_ADMIN_PASSWORD=secret
      # http://docs.grafana.org/auth/overview/#anonymous-authentication
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

volumes:
  data:
    labels:
      - de.felixhummel.project=x-apm-timescaledb
  grafana_data:
    labels:
      - de.felixhummel.project=x-apm-timescaledb
