version: '3.5'

services:
  xinput:
    image: felix/x-apm-timescaledb
    user: 1337:1337
    environment:
      - DISPLAY=${DISPLAY-:0.0}
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=password
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stop_signal: SIGINT
    restart: always
  db:
    image: timescale/timescaledb:latest-pg10
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql/create_and_hypertable.sql:/docker-entrypoint-initdb.d/z_01_create_and_hypertable.sql
      - ./sql/annotations.sql:/docker-entrypoint-initdb.d/z_02_annotations.sql
    restart: always
  grafana:
    image: grafana/grafana:5.3.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  data:
    labels:
      - de.felixhummel.project=x-apm-timescaledb
  grafana_data:
    labels:
      - de.felixhummel.project=x-apm-timescaledb
