version: '3.5'

services:
  db:
    image: timescale/timescaledb
    ports:
      - ${PGPORT}:5432
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
