version: '3.5'

networks:
  ingress:
    external: true

services:

  nginx:
    image: nginx:1.21
    networks:
      default:
      ingress:
        aliases:
          - grafana.apm.f.internal
    volumes:
      - ./etc_nginx/:/etc/nginx/:ro
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 5s
      timeout: 1s
    restart: unless-stopped
  xinput:
    image: felix/x-apm-timescaledb
    user: 1337:1337
    environment:
      - DISPLAY=${DISPLAY-:0.0}
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=password
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stop_signal: SIGINT
    restart: unless-stopped
  db:
    image: timescale/timescaledb:latest-pg10
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql/create_and_hypertable.sql:/docker-entrypoint-initdb.d/z_01_create_and_hypertable.sql
      - ./sql/annotations.sql:/docker-entrypoint-initdb.d/z_02_annotations.sql
    restart: unless-stopped
  grafana:
    image: grafana/grafana:7.3.4
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # http://docs.grafana.org/auth/overview/#anonymous-authentication
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

volumes:
  data:
    labels:
      - de.felixhummel.project=x-apm-timescaledb
  grafana_data:
    labels:
      - de.felixhummel.project=x-apm-timescaledb
