#!/bin/bash
set -euo pipefail

# wait for DB
_wait.sh psql -h $PGHOST -p $PGPORT $PGDATABASE $PGUSER -c 'select 1 as ok'

# wait for xserver (unlimited)
TIMEOUT=0 SLEEP=5 _wait.sh xinput

# run the pipeline
x-action-log | xinput2insert.sh | load.sh
