#!/bin/bash
# prints "<timestamp> <event type>" lines for all X input events
# event types:
# "m" for mouse button press
# "k" for keyboard button press

hash xinput

IFS='' xinput test-xi2 --root | grep -E --line-buffered '^EVENT type (2|4)' | while read line; do
  # line examples:
  # EVENT type 4 (ButtonPress)
  # EVENT type 2 (KeyPress)
  dt_ms=$(date +%FT%H:%M:%S.%N | cut -b1-23)
  if echo $line | grep -q '(ButtonPress)'; then
    echo $dt_ms m
  elif echo $line | grep -q '(KeyPress)'; then
    echo $dt_ms k
  fi
done
