#!/bin/bash
# prints "<timestamp> <event type>" lines for all X input events
# event types:
# "m" for mouse button press
# "k" for keyboard button press

hash xinput

# https://stackoverflow.com/a/28333938/241240
trap "kill 0" SIGINT

apm-mouse &
apm-keyboard &
wait
