apiVersion: 1

# http://docs.grafana.org/features/datasources/postgres/#configure-the-datasource-with-provisioning
datasources:
  - name: TimescaleDB
    type: postgres
    url: db:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: "password"
    jsonData:
      sslmode: "disable"
      postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
